language: cpp
sudo: true

before_install:
  - sudo add-apt-repository --yes ppa:ubuntu-toolchain-r/test     # newer toolchain
  - sudo apt-add-repository --yes ppa:zoogie/sdl2-snapshots       # libsdl2
  - export PATH=~/usr/bin:$PATH
  - echo $CXX
  - $CXX --version

install:
  - export CXX=g++-5
  - export CXX_FLAGS="${CXX_FLAGS} -Wall -Wextra -Werror -Weffc++ -Wlogical-op -Wshadow"
  - export CXX_FLAGS="${CXX_FLAGS} -fsanitize=${ASAN} -fno-omit-frame-pointer"
  - sudo apt-get update -qq
  - sudo apt-get install -q -y libsdl2-dev libsdl2-image-dev g++-5
  # premake5
  - wget https://github.com/premake/premake-core/releases/download/v5.0.0-alpha8/premake-5.0.0-alpha8-src.zip -O premake.zip
  - unzip premake.zip
  - cd premake-5.0.0-alpha6/build/gmake.unix
  - make config=release
  - cd ../../..
  - mv premake-5.0.0-alpha6/bin/release/premake5 premake5
script:
  - ../premake5 gmake
  - make

notifications:
  email: false
