# GNU Make workspace makefile autogenerated by Premake

.NOTPARALLEL:

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  SpaceShooterMidterm_config = debug
endif
ifeq ($(config),release)
  SpaceShooterMidterm_config = release
endif

PROJECTS := SpaceShooterMidterm

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

SpaceShooterMidterm:
ifneq (,$(SpaceShooterMidterm_config))
	@echo "==== Building SpaceShooterMidterm ($(SpaceShooterMidterm_config)) ===="
	@${MAKE} --no-print-directory -C . -f SpaceShooterMidterm.make config=$(SpaceShooterMidterm_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f SpaceShooterMidterm.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   SpaceShooterMidterm"
	@echo ""
	@echo "For more information, see http://industriousone.com/premake/quick-start"